### ISSUE TITLE
v430 becomes valid on the 3rd July 2017

### ISSUE THREAD

**Issue by pauldambra** [pauldambra/ModulusChecker#17]
Dear Customer 

You have signed up to receive email notifications when a new version of the ‘Validating account numbers: UK modulus checking’ specification is updated. 

This mail is to inform you that the specification and associated table have been updated and are available for download [here.](https://www.vocalink.com/customer-support/modulus-checking/?utm_campaign=MODCHECK%20-%201706%20-%20WR%20-%20New%20Template&utm_medium=email&utm_source=Eloqua&elqTrackId=de625e715a354db895d6c0adcd1294aa&elq=2f87fef950c04dcb90b8bebbe078a472&elqaid=793&elqat=1&elqCampaignId=1690) 

The specification will be valid from 3rd July 2017, however please note that modulus checking information may be in the specification for sorting codes that are not currently set up. All sorting codes should be checked against the current industry sorting code directory (ISCD) or the extended industry sorting code directory (EISCD) to ensure they are valid. 

If you have any queries, wish to cancel these notifications or amend the email address the notifications are sent to please contact Diana Pirtea on 0203 818 2142 or reply to this email.

**Comment by AlmostTypical** [comment]
Hi Paul!

I've created a forked branch with an updated version of the Vocalink spec that covers both this and issue #16, and updates the expected result of the CanGetRuleMappings test to match the new spec. Would it be helpful to create a pull request for that now or would it be preferable to wait until 3rd July? 🙂

**Comment by pauldambra** [comment]
That's awesome! Thanks!

Yeah, create the PR now and then if there're any changes needed we've got time to get them in before the 3rd without rushing.

**Comment by pauldambra** [comment]
closed by #18
