### ISSUE TITLE
Modulus check failing on account and sort code combination when called for the second time. 

### ISSUE THREAD

**Issue by mohammadshahabrafiq** [pauldambra/ModulusChecker#5]
Hello there,

I am using this modulus checker and have come across a scenario where the checker is not working as expected. I have written a unit test to demonstrate.

```
[Test]
public void GivenASortCodeAndAccountNumberCombinationWhenCheckedForTheSecondTimeThenItShlouldPassValidation()
{
    var sortcode = "775024";
    var accNumber = "26862368";

    var checker = new ModulusChecker();

    Assert.IsTrue(checker.CheckBankAccount(sortcode, accNumber));
    Assert.IsTrue(checker.CheckBankAccount("776203", "01193899"));
    Assert.IsTrue(checker.CheckBankAccount(sortcode, accNumber));
}
```

I think the problem lies in ModulusWeightTable.cs on line 15 and 16 where the ModulusWeightTable instance is a singleton being held in the static variable named Instance. When I modify the code so the GetInstance property returns a new instance of ModulusWeightTable on every call then it works fine. I wonder whether the singleton is getting into an invalid state?

Best regards

Mohammad

**Comment by pauldambra** [comment]
Really appreciate the test case! I'll take a look tomorrow or over the weekend. You're welcome to raise a pull request if you have time. No worries if not.

**Comment by pauldambra** [comment]
Logging an MD5 hash of the ModulusWeightTable each time the check is requested returns

```
Modulus weight table is: AC83FE74A5AA09AF27FD7C4348E9C259
Modulus weight table is: AC83FE74A5AA09AF27FD7C4348E9C259
Modulus weight table is: F8E8FDF269C26F26F8A667534059F27E
```

o_O

**Comment by pauldambra** [comment]
shouldn't do this tired :/ PRs #6 #7 and #8 fix the bug and then setup CI ready to publish the package

built in https://ci.appveyor.com/project/pauldambra/moduluschecker/build/1.3.1.64

**Comment by pauldambra** [comment]
released to nuget https://www.nuget.org/packages/ModulusChecker/1.3.1

let me know if there's any problems. And again thanks for the test case 🎖

**Comment by mohammadshahabrafiq** [comment]
No worries. You are very welcome. Sorry I couldn't help out much I just felt the problem was way down in the modulus checker algorithm somewhere and I didn't have time to go delving.
